### ISSUE TITLE
[Bug report] The initialized VuePress project has errors

### ISSUE THREAD

**Issue by XY0797** [vuepress/ecosystem#410]
### Description

Use the following command to create a VuePress project
```
npm init vuepress vuepress-starter
```
Select `简体中文`, `npm`, and leave other options as default
Start the project and you will see the following error:
![Image](https://github.com/user-attachments/assets/8733fc04-fe24-48d8-b0d9-a701c05eb61a)

### Reproduction

See `description` for details.

### Used Package Manager

npm

### System Info

```shell
Windows 11 Pro 24H2
```

**Comment by XY0797** [comment]
According to the prompt, executing `npm install -D sass-embedded` can solve the problem. However, as a project initialization tool, create-vuepress should not generate projects with errors.

**Comment by Mister-Hope** [comment]
Fixed

**Comment by XY0797** [comment]
@Mister-Hope The problem still exists, and it's even more serious!
I cleaned the `npm-cache` and retested `npm init vuepress vuepress-starter`, and got the following result:
```
F:\initvp>npm init vuepress vuepress-starter
Need to install the following packages:
create-vuepress@2.0.0-rc.87
Ok to proceed? (y)


> npx
> create-vuepress vuepress-starter

✔ Select a language to display / 选择显示语言 简体中文
✔ 选择包管理器 npm
✔ 你想要使用哪个打包器？ vite
✔ 你想要创建什么类型的项目？ blog
生成 package.json...
✔ 设置应用名称 my-vuepress-site
✔ 设置应用描述 A VuePress project
✔ 设置应用版本号 0.0.1
✔ 设置协议 MIT
file:///C:/Users/****/AppData/Local/npm-cache/_npx/3f091d7c366309f0/node_modules/create-vuepress/lib/index.js:2
import{createCommand as P}from"commander";import{readdirSync as w,mkdirSync as q,statSync as D,writeFileSync as h,readFileSync as k,existsSync as C}from"node:fs";import{dirname as x,join as u,resolve as W}from"node:path";import{select as g,input as v,confirm as z}from"@inquirer/prompts";import{execaCommandSync as d,execaCommand as E}from"execa";import{fileURLToPath as G}from"node:url";const j={hope:"create-vuepress-theme-hope"},f=e=>{try{w(e)}catch{try{q(e,{recursive:!0})}catch{}}},T=(e,s)=>{const t=x(s);f(t),h(s,k(e))},M=(e,s)=>{f(s),w(e,{withFileTypes:!0}).forEach(t=>{t.isFile()?T(`${e}/${t.name}`,`${s}/${t.name}`):t.isDirectory()&&M(`${e}/${t.name}`,`${s}/${t.name}`)})},_=(e,s)=>{D(e).isDirectory()?M(e,s):D(e).isFile()&&T(e,s)},F=()=>{try{return d("pnpm --version",{stdio:"ignore"}).exitCode===0}catch{return!1}},O=()=>{try{return d("yarn --version",{stdio:"ignore"}).exitCode===0}catch{return!1}},S=["npm"];O()&&S.unshift("yarn"),F()&&S.unshift("pnpm");const A=e=>g({message:e,choices:S.map(s=>({name:s,value:s}))}),N="https://registry.npmmirror.com/",H=(e,s)=>d(`${e} config get ${s?"npmRegistryServer":"registry"}`).stdout,I=async(e,s)=>{const t=e==="yarn"&&!d("yarn --version").stdout.startsWith("1"),o=H(e,t);return/https:\/\/registry\.npm\.taobao\.org\/?/.test(o)&&(console.error("npm.taobao.org is no longer available, resetting it to npmmirror.com"),d(`${e} config set ${t?"npmRegistryServer":"registry"} ${N}`)),s==="zh"?g({message:"选择你想使用的源",choices:[{name:"国内镜像源",value:N},{name:"当前源",value:o}]}):o},y="vuepress-theme-",Y=e=>{const s=e.match(/^@(.*)\/(.*)$/);if(s===null)return e.startsWith(y)?e:`${y}${e}`;const[,t,o]=s;return t==="vuepress"?o.startsWith("theme-")?e:`@vuepress/theme-${o}`:o.startsWith(y)?e:`@${t}/${y}${o}`},J=JSON.parse(k(G(import.meta.resolve("create-vuepress/package.json")),"utf-8")),{devDependencies:m,version:R}=J,U=/^(?:@[a-z0-9-*~][a-z0-9-*._~]*\/)?[a-z0-9-~][a-z0-9-._~]*$/u,V=/^[0-9]+\.[0-9]+\.(?:[0-9]+|[0-9]+-[a-z]+\.[0-9])$/u,B=async({targetDir:e,packageManager:s,locale:t,preset:o,bundler:i})=>{const r=u(e,"package.json");console.info(t.flow.createPackage);const n=await v({message:t.question.name,default:"my-vuepress-site",validate:$=>U.exec($)?!0:t.error.name}),c=await v({message:t.question.description,default:"A VuePress project"}),a=await v({message:t.question.version,default:"0.0.1",validate:$=>V.exec($)?!0:t.error.version}),l=await v({message:t.question.license,default:"MIT"}),p={name:n,description:c,version:a,license:l,type:"module",scripts:{"docs:build":"vuepress build docs","docs:clean-dev":"vuepress dev docs --clean-cache","docs:dev":"vuepress dev docs","docs:update-package":`${s==="npm"?"npx":`${s} dlx`} vp-update`},devDependencies:{[`@vuepress/bundler-${i}`]:m.vuepress,"@vuepress/theme-default":m["@vuepress/theme-default"],"sass-embedded":m["sass-embedded"],...i==="webpack"?{"sass-loader":m["sass-loader"]}:{},vue:m.vue,vuepress:m.vuepress,...o==="blog"?{"@vuepress/plugin-blog":m["@vuepress/plugin-blog"]}:{}}};h(r,`${JSON.stringify(p,null,2)}










TypeError: Cannot read properties of undefined (reading 'vuepress')
    at B (file:///C:/Users/****/AppData/Local/npm-cache/_npx/3f091d7c366309f0/node_modules/create-vuepress/lib/index.js:2:2743)
    at async Command.oe (file:///C:/Users/****/AppData/Local/npm-cache/_npx/3f091d7c366309f0/node_modules/create-vuepress/lib/index.js:64:1048)
    at async Command.parseAsync (C:\Users\****\AppData\Local\npm-cache\_npx\3f091d7c366309f0\node_modules\commander\lib\command.js:1104:5)
    at async file:///C:/Users/****/AppData/Local/npm-cache/_npx/3f091d7c366309f0/node_modules/create-vuepress/lib/index.js:69:90

Node.js v22.14.0
npm error code 1
npm error path F:\initvp
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c create-vuepress vuepress-starter
npm notice
npm notice New major version of npm available! 10.9.2 -> 11.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.2.0
npm notice To update run: npm install -g npm@11.2.0
npm notice
npm error A complete log of this run can be found in: C:\Users\****\AppData\Local\npm-cache\_logs\2025-03-25T07_57_36_117Z-debug-0.log
```
To rule out the suspicion of `npmmirror`, I removed the `registry` configuration in `.npmrc` and cleaned the `npm-cache` again, then ran the command once more. Unfortunately, the error persisted, and the logs were identical except for the different URL.
Below is the log file:
[2025-03-25T07_57_36_117Z-debug-0.log](https://github.com/user-attachments/files/19444103/2025-03-25T07_57_36_117Z-debug-0.log)

**Comment by XY0797** [comment]
the bug of `2.0.0-rc.88`
```
node:fs:1740
  const stats = binding.stat(
                        ^

Error: ENOENT: no such file or directory, stat 'F:\initvp\file:\F:\initvp\node_modules\create-vuepress\template\docs'
    at statSync (node:fs:1740:25)
    at _ (file:///F:/initvp/node_modules/create-vuepress/lib/index.js:2:693)
    at Q (file:///F:/initvp/node_modules/create-vuepress/lib/index.js:52:180)
    at async Command.oe (file:///F:/initvp/node_modules/create-vuepress/lib/index.js:64:1116)
    at async Command.parseAsync (F:\initvp\node_modules\commander\lib\command.js:1104:5)
    at async file:///F:/initvp/node_modules/create-vuepress/lib/index.js:69:90 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'F:\\initvp\\file:\\F:\\initvp\\node_modules\\create-vuepress\\template\\docs'
}
```

**Comment by Mister-Hope** [comment]
This is weird, the folder exists on npm: 

![Image](https://github.com/user-attachments/assets/94e642d0-a8ef-4a6f-9b0a-aa89681703e6)

**Comment by Mister-Hope** [comment]
Let's see if rc.89 fixes this.
